"""Symbol-shell declaration table -> declarations.json (M4, plan SS4).

Inputs:
- the SymbolDefinition entries of ``all_entries`` (228 in this snapshot;
  48 carry a domain/codomain Table -- far fewer than the live fungrim.org,
  so usage-derived signatures supplement the table-derived ones),
- the in-memory translation result (corpus + properties records) for the
  head/atom census, call-site arities and per-argument type evidence,
- ``ce-known-symbols.txt``: the oracle of names the Compute Engine already
  defines, generated by ``npx tsx grim2mathjson/gen_ce_known.ts`` (keeps
  the two repos decoupled, plan SS4 "Filtering").

Output ``<out>/declarations.json``:

    {
      "generator": "...",
      "declarations": { <name>: {
          "fungrimId":       SymbolDefinition entry id | null,
          "fungrimNames":    source names when != <name> (e.g. PP->Primes),
          "description":     SymbolDefinition text | null,
          "arity":           int | [min, max] | null (atoms),
          "signature":       CE type string (feeds ce.declare directly),
          "signatureSource": "verified" | "table" | "usage" | "curated"
                             | "fallback",
          "signatureInferred": false only for "fallback",
          "domainTable":     translated Table rows | null,
          "wikidata":        null (hand-curated overlay is M6)
      } },
      "existing": { <CE-known name used by the corpus>: {
          "fungrimNames": [...], "note": ... } }
    }

Signature priority (first applicable wins):
1. ``verified``  -- mapping.VERIFIED_SHELLS, ce.declare-verified in the M0
   spike (incl. the boolean predicates Element's EL-3 form requires).
2. ``table``     -- derived from the "Numbers" rows of the entry's domain
   Table via the set->type map below; per-position join across rows;
   trailing positions beyond the minimum corpus call-site arity are
   marked optional (``integer?``).
3. ``curated``   -- hand-table for heads whose first argument is a
   function literal (generator/extremum heads emitted by structural.py)
   and for non-numeric atoms/domains; documented inline.
4. ``usage``     -- parameter types joined from corpus call sites
   (literal ints -> integer, variables -> the type of their Element
   assumption domain); codomain "complex" (Fungrim shells are
   number-valued unless curated otherwise).
5. ``fallback``  -- ``(any+) -> any`` / ``any``; signatureInferred false.

The mechanical coverage cross-check (M4 acceptance) lives in
:func:`build`: every head/atom occurring in an emitted expression that is
neither CE-known nor a per-entry variable MUST be covered by the
declarations table; leftovers are returned for the caller to fail on.
"""

import json
import os
import re

from . import mapping
from . import walker
from . import __version__

GENERATOR = f"grim2mathjson {__version__}"

_FUSED_SUBSCRIPT = re.compile(r"^(.+?)_\d+$")

# Type-width join order (CE numeric tower fragment used here).
_TYPE_ORDER = ["integer", "rational", "real", "complex"]


def _join(a, b):
    if a is None:
        return b
    if b is None:
        return a
    if a == b:
        return a
    if a in _TYPE_ORDER and b in _TYPE_ORDER:
        return _TYPE_ORDER[max(_TYPE_ORDER.index(a), _TYPE_ORDER.index(b))]
    return "any"


# ---------------------------------------------------------------------------
# SymbolDefinition harvesting (pygrim Exprs)
# ---------------------------------------------------------------------------

def _named_parts(entry):
    out = {}
    for a in entry.args():
        if not a.is_atom():
            h = a.head()
            if h.is_atom() and h.is_symbol():
                out.setdefault(h._symbol, []).append(a)
    return out


def collect_symbol_definitions(entries):
    """name -> {"id", "example" (Expr), "description", "table" (Expr|None)}
    for every non-Formula SymbolDefinition entry."""
    defs = {}
    for e in entries:
        p = _named_parts(e)
        if "SymbolDefinition" not in p or "Formula" in p:
            continue
        sd = p["SymbolDefinition"][0]
        sym = sd.args()[0]
        if not (sym.is_atom() and sym.is_symbol()):
            continue
        eid = p["ID"][0].args()[0]._text if "ID" in p else None
        example = sd.args()[1] if len(sd.args()) > 1 else None
        descr = None
        if len(sd.args()) > 2 and sd.args()[2].is_text():
            descr = sd.args()[2]._text
        table = p["Table"][0] if "Table" in p else None
        defs[sym._symbol] = {
            "id": eid, "example": example,
            "description": descr, "table": table,
        }
    return defs


# ---------------------------------------------------------------------------
# Corpus census: names, arities, per-position type evidence
# ---------------------------------------------------------------------------

_CONSTANT_TYPES = {
    "Pi": "real", "ExponentialE": "real", "EulerGamma": "real",
    "CatalanConstant": "real", "GoldenRatio": "real",
    "PositiveInfinity": "real", "NegativeInfinity": "real",
    "ImaginaryUnit": "complex", "ComplexInfinity": "complex",
}

_DOMAIN_TYPES = {
    "Integers": "integer", "NonNegativeIntegers": "integer",
    "PositiveIntegers": "integer", "NonPositiveIntegers": "integer",
    "Primes": "integer", "RationalNumbers": "rational",
    "RealNumbers": "real", "ComplexNumbers": "complex",
    "HH": "complex", "AlgebraicNumbers": "complex",
}


def _domain_type(d):
    """CE type of a translated membership domain (None when not numeric)."""
    if isinstance(d, str):
        return _DOMAIN_TYPES.get(d)
    if isinstance(d, list) and d and isinstance(d[0], str):
        if d[0] in ("Interval",):
            return "real"
        if d[0] in ("Range", "Divisors"):
            return "integer"
        if d[0] == "SetMinus":
            return _domain_type(d[1])
        if d[0] == "Union":
            t = None
            for a in d[1:]:
                t = _join(t, _domain_type(a))
            return t
    return None


# Encoding markers that are not standalone symbols: "Open" only exists as
# Interval endpoint syntax (["Interval", ["Open", a], b], spike #10) and is
# interpreted positionally by CE's Interval -- it needs no declaration.
_STRUCTURAL_MARKERS = frozenset(["Open"])


class Census:
    """Names/arities/argument-type evidence over the emitted expressions."""

    def __init__(self):
        self.heads = {}        # name -> set of arities
        self.atoms = set()
        self.arg_types = {}    # name -> {position: joined type | None}

    def _record_call(self, name, args, var_types):
        self.heads.setdefault(name, set()).add(len(args))
        slots = self.arg_types.setdefault(name, {})
        for i, a in enumerate(args):
            t = None
            if isinstance(a, int):
                t = "integer"
            elif isinstance(a, dict) and "num" in a:
                t = "real"
            elif isinstance(a, str):
                t = var_types.get(a) or _CONSTANT_TYPES.get(a)
            if t is not None:
                slots[i] = _join(slots.get(i), t)
            else:
                slots.setdefault(i, None)

    def scan_record(self, record, presumed_variables=None):
        """Census one corpus/property record.

        Bound names are collected record-wide first (a binder's body is a
        *sibling* of the binding form -- ["Sum", body, ["Limits", "k", ...]]
        -- so lexical-scope tracking would miss the body occurrences; a
        record-local name never doubles as a shell head, so record-wide
        exclusion is safe).

        ``presumed_variables``: property records carry no ``variables``
        list (the M2 micro-format is frozen), so free parameter names
        (q, chi, ...) cannot be excluded structurally; the caller passes
        the known-vocabulary set and anything outside it is presumed to
        be a variable. Their function heads are all explicit vocabulary,
        so shell coverage is unaffected.
        """
        excluded = set(record.get("variables") or [])
        excluded |= set(record.get("indexedFamilies") or [])
        if record.get("var"):
            excluded.add(record["var"])

        def expr_fields():
            for field in ("formula", "assumptions", "expr", "domain",
                          "point", "condition", "value"):
                v = record.get(field)
                if v is not None:
                    yield v
            # alternative assumption sets (list of exprs; the scanners
            # treat a non-symbol head as a transparent container)
            for v in record.get("assumptionAlternatives") or []:
                yield v
            for v in record.get("path") or []:
                yield v

        # pass 1: record-wide binder collection
        def collect_binders(x):
            if not isinstance(x, list) or not x:
                return
            head = x[0]
            if isinstance(head, str):
                if head == "Function":
                    excluded.update(a for a in x[2:] if isinstance(a, str))
                elif head in ("Limits", "ForAll", "Exists", "Element") \
                        and len(x) > 1 and isinstance(x[1], str):
                    # statement-position Element vars are free (already in
                    # `variables`); indexing-set vars are bound -- both are
                    # record-local names, so excluding both is safe.
                    excluded.add(x[1])
            for a in (x if not isinstance(head, str) else x[1:]):
                collect_binders(a)

        for v in expr_fields():
            collect_binders(v)

        # variable -> type evidence from every ["Element", var, S] in the
        # record: assumption conjuncts AND indexing sets inside the formula
        # (a Sum's bound index has its domain in the indexing set, not the
        # assumptions).
        var_types = {}
        def collect_types(x):
            if not isinstance(x, list) or not x:
                return
            if x[0] == "Element" and len(x) >= 3 and isinstance(x[1], str):
                t = _domain_type(x[2])
                if t is not None:
                    var_types[x[1]] = _join(var_types.get(x[1]), t)
            if x[0] in ("Sum", "Product", "Integrate"):
                # ["Limits", v, lo, hi]: discrete for Sum/Product,
                # continuous for Integrate
                for a in x[1:]:
                    if isinstance(a, list) and len(a) >= 2 \
                            and a[0] == "Limits" and isinstance(a[1], str):
                        t = "integer" if x[0] != "Integrate" else "real"
                        var_types[a[1]] = _join(var_types.get(a[1]), t)
            for a in x:
                collect_types(a)
        for v in expr_fields():
            collect_types(v)

        def is_excluded(name):
            if name in excluded:
                return True
            m = _FUSED_SUBSCRIPT.match(name)
            if m and (m.group(1) in excluded
                      or m.group(1) + "_" in excluded):
                return True  # fused subscript symbol (z_1 of variable z)
            if presumed_variables is not None \
                    and name not in presumed_variables:
                return True
            return False

        # pass 2: heads/atoms census
        def scan(x):
            if isinstance(x, str):
                if not is_excluded(x):
                    self.atoms.add(x)
                return
            if not isinstance(x, list) or not x:
                return
            head = x[0]
            if isinstance(head, str):
                if head in _STRUCTURAL_MARKERS:
                    for a in x[1:]:
                        scan(a)
                    return
                if not is_excluded(head) and not head.endswith("_"):
                    self._record_call(head, x[1:], var_types)
                for a in x[1:]:
                    scan(a)
            else:
                for a in x:
                    scan(a)

        for v in expr_fields():
            scan(v)

    def all_names(self):
        return set(self.heads) | self.atoms


def run_census(result, vocabulary):
    census = Census()
    for records in result["corpus"].values():
        for r in records:
            census.scan_record(r)
    for r in result["properties"]:
        census.scan_record(r, presumed_variables=vocabulary)
    return census


# ---------------------------------------------------------------------------
# Table-derived signatures
# ---------------------------------------------------------------------------

def _head_name(e):
    if e.is_atom():
        return None
    h = e.head()
    return h._symbol if (h.is_atom() and h.is_symbol()) else None


def _fungrim_set_type(S):
    """CE type of a Fungrim domain-set Expr (None: not a plain number set)."""
    if S.is_atom() and S.is_symbol():
        return {"ZZ": "integer", "QQ": "rational", "RR": "real",
                "CC": "complex", "PP": "integer", "HH": "complex",
                "AlgebraicNumbers": "complex"}.get(S._symbol)
    h = _head_name(S)
    if h in ("ZZGreaterEqual", "ZZLessEqual", "Range"):
        return "integer"
    if h in ("OpenInterval", "ClosedInterval", "OpenClosedInterval",
             "ClosedOpenInterval"):
        return "real"
    if h == "SetMinus":
        return _fungrim_set_type(S.args()[0])
    if h == "Union":
        t = None
        for a in S.args():
            ta = _fungrim_set_type(a)
            if ta is None:
                return None
            t = _join(t, ta)
        return t
    return None


def _table_rows(table):
    """Yield (section, P, Q) for each Tuple(P, Q) row of a domain Table."""
    rows = []
    for a in table.args():
        if _head_name(a) == "List":
            section = None
            for item in a.args():
                ih = _head_name(item)
                if ih == "TableSection":
                    section = item.args()[0]._text \
                        if item.args() and item.args()[0].is_text() else None
                elif ih == "Tuple" and len(item.args()) == 2:
                    rows.append((section, item.args()[0], item.args()[1]))
    return rows


def _flatten_and(P):
    if _head_name(P) == "And":
        out = []
        for a in P.args():
            out.extend(_flatten_and(a))
        return out
    return [P]


def signature_from_table(name, fungrim_names, table, min_arity):
    """(params, codomain) derived from the "Numbers" rows, or None.

    Rows mentioning power series / infinities / structural domains yield no
    type via _fungrim_set_type and are excluded from the primary signature
    (they remain visible in the emitted domainTable)."""
    by_arity = {}
    codomain = None
    for section, P, Q in _table_rows(table):
        if section not in (None, "Numbers"):
            continue
        if _head_name(Q) != "Element" or len(Q.args()) != 2:
            continue
        call, cod = Q.args()
        if call.is_atom():
            # atom definition row: Element(C, RR) etc.
            if call.is_symbol() and call._symbol in fungrim_names:
                t = _fungrim_set_type(cod)
                if t is not None:
                    codomain = _join(codomain, t)
            continue
        if _head_name(call) not in fungrim_names:
            continue
        args = call.args()
        if any(not (a.is_atom() and a.is_symbol()) for a in args):
            continue
        # build per-arg types from P's Element conjuncts
        elems = {}
        for c in _flatten_and(P):
            if _head_name(c) == "Element" and len(c.args()) == 2 \
                    and c.args()[0].is_atom() and c.args()[0].is_symbol():
                elems[c.args()[0]._symbol] = c.args()[1]
        types = []
        for a in args:
            S = elems.get(a._symbol)
            t = _fungrim_set_type(S) if S is not None else None
            if t is None:
                types = None
                break
            types.append(t)
        if types is None:
            continue
        cod_t = _fungrim_set_type(cod)
        if cod_t is None:
            continue
        slots = by_arity.setdefault(len(types), [None] * len(types))
        for i, t in enumerate(types):
            slots[i] = _join(slots[i], t)
        codomain = _join(codomain, cod_t)
    if not by_arity:
        if codomain is not None:
            return ([], codomain)  # atom (constant) definition
        return None
    max_arity = max(by_arity)
    params = [None] * max_arity
    for arity, slots in by_arity.items():
        for i, t in enumerate(slots):
            params[i] = _join(params[i], t)
    params = [t or "any" for t in params]
    optional_from = min(min(by_arity), min_arity or max_arity)
    params = [t + "?" if i >= optional_from else t
              for i, t in enumerate(params)]
    return (params, codomain or "complex")


def translated_domain_table(table):
    """All Table rows as MathJSON (untranslatable rows keep source strings)."""
    out = []
    for section, P, Q in _table_rows(table):
        row = {"section": section}
        for key, expr in (("domain", P), ("codomain", Q)):
            try:
                row[key] = walker.walk(expr, walker.Ctx())
            except (walker.TranslationSkip, walker.UnknownHeadError):
                row[key] = None
                row[key + "Source"] = str(expr)
        out.append(row)
    return out or None


# ---------------------------------------------------------------------------
# Curated signatures (heads structural.py emits with Function-literal
# arguments, plus non-numeric atoms/domains). Sources: structural.py
# encodings (spike #12/#13 and translate_optimum) and the head semantics.
# ---------------------------------------------------------------------------

CURATED_SIGNATURES = {
    # generator/metadata heads in expression position:
    #   [head, ["Function", body, var], extra...]
    "Zeros": "(function, any*) -> set<complex>",
    "Poles": "(function, any*) -> set<complex>",
    "BranchPoints": "(function, any*) -> set<complex>",
    "BranchCuts": "(function, any*) -> collection",
    "EssentialSingularities": "(function, any*) -> set<complex>",
    "Residue": "(function, any*) -> complex",
    "AnalyticContinuation": "(function, any*) -> complex",
    "ComplexZeroMultiplicity": "(function, any*) -> integer",
    "Solutions": "(function, any*) -> collection",
    "UniqueSolution": "(function, any*) -> complex",
    "UniqueZero": "(function, any*) -> complex",
    "IsHolomorphic": "(function, any*) -> boolean",
    "IsMeromorphic": "(function, any*) -> boolean",
    # arg-extrema / sequence-limit shells (Function-literal first argument)
    "ArgMin": "(function, collection, any*) -> set",
    "ArgMax": "(function, collection, any*) -> set",
    "ArgMinUnique": "(function, collection, any*) -> any",
    "ArgMaxUnique": "(function, collection, any*) -> any",
    "SequenceLimitInferior": "(function, any) -> any",
    "SequenceLimitSuperior": "(function, any) -> any",
    # predicates (boolean-typed so EL-3 conditions and statements box)
    "AsymptoticTo": "(any, any, any, any) -> boolean",
    "EqualNearestDecimal": "(any, any, integer) -> boolean",
    "NearestDecimal": "(any, integer) -> any",
    "ComplexIndefiniteIntegralEqual": "(any, any, any, any?) -> boolean",
    "RealIndefiniteIntegralEqual": "(any, any, any, any?) -> boolean",
    "IndefiniteIntegralEqual": "(any, any, any, any?) -> boolean",
    # domains / regions / structural collections
    "Lattice": "(any+) -> collection",
    "Matrices": "(any+) -> collection",
    "GeneralLinearGroup": "(integer, collection) -> collection",
    "SpecialLinearGroup": "(integer, collection) -> collection",
    "CartesianPower": "(collection, integer) -> collection",
    "Interior": "(collection) -> collection",
    "InteriorClosure": "(collection) -> collection",
    "OpenDisk": "(complex, real) -> set<complex>",
    "ClosedDisk": "(complex, real) -> set<complex>",
    "BernsteinEllipse": "(real) -> set<complex>",
    "UnitCircle": "set<complex>",
    "ModularGroupFundamentalDomain": "set<complex>",
    "ModularLambdaFundamentalDomain": "set<complex>",
    "PSL2Z": "collection",
    "ModularGroupAction": "(any, complex) -> complex",
    "PrimitiveDirichletCharacters": "(integer) -> collection",
    "PrimitiveReducedPositiveIntegralBinaryQuadraticForms":
        "(integer) -> collection",
    # propositions / non-numeric atoms
    "RiemannHypothesis": "boolean",
    "GeneralizedRiemannHypothesis": "boolean",
    "Rings": "collection",
    "Fields": "collection",
    # real constants without CE equivalents
    "ConstGlaisher": "real",
    "HalphenConstant": "real",
    "DeBruijnNewmanLambda": "real",   # the de Bruijn-Newman constant
    # textbook signatures for heads whose corpus call sites carry no
    # variable-type evidence (all arguments are compound expressions)
    "UpperGamma": "(complex, complex) -> complex",   # incomplete Gamma(a, z)
    "RiemannXi": "(complex) -> complex",
}


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

def _arity_field(arities):
    if not arities:
        return None
    lo, hi = min(arities), max(arities)
    return lo if lo == hi else [lo, hi]


def _usage_signature(name, census):
    arities = census.heads.get(name)
    if not arities:
        return None
    slots = census.arg_types.get(name, {})
    lo, hi = min(arities), max(arities)
    params = []
    for i in range(hi):
        t = slots.get(i) or "any"
        if i >= lo:
            t += "?"
        params.append(t)
    if any(slots.get(i) for i in range(hi)):
        return (params, "complex")
    return None


def build(result, entries, ce_known):
    """Returns (declarations_doc, uncovered_names).

    declarations_doc is the deterministic dict written to
    declarations.json; uncovered_names is the mechanical-coverage residue
    (must be empty for the M4 acceptance)."""
    shell_universe = set(mapping.SHELL_HEADS)
    census = run_census(result, vocabulary=shell_universe | set(ce_known))
    symdefs = collect_symbol_definitions(entries)

    # reverse SYMBOL_MAP: emitted name -> fungrim source names
    reverse = {}
    for src, dst in mapping.SYMBOL_MAP.items():
        if src != dst:
            reverse.setdefault(dst, []).append(src)

    names = census.all_names()

    to_declare = sorted(n for n in names
                        if n not in ce_known and n in shell_universe)
    uncovered = sorted(n for n in names
                       if n not in ce_known and n not in shell_universe)

    declarations = {}
    for name in to_declare:
        fungrim_names = [name] + sorted(reverse.get(name, []))
        sd = next((symdefs[fn] for fn in fungrim_names if fn in symdefs),
                  None)
        arities = census.heads.get(name, set())
        is_function = bool(arities)
        if sd is not None and sd["example"] is not None \
                and not sd["example"].is_atom():
            arities = set(arities) | {len(sd["example"].args())}

        signature = None
        source = None
        domain_table = None
        if sd is not None and sd["table"] is not None:
            domain_table = translated_domain_table(sd["table"])

        if name in mapping.VERIFIED_SHELLS:
            signature = mapping.VERIFIED_SHELLS[name]
            source = "verified"
        if signature is None and sd is not None and sd["table"] is not None:
            derived = signature_from_table(
                name, set(fungrim_names), sd["table"],
                min(arities) if arities else None)
            if derived is not None:
                params, codomain = derived
                signature = f"({', '.join(params)}) -> {codomain}" \
                    if params else codomain
                source = "table"
        if signature is None and name in CURATED_SIGNATURES:
            signature = CURATED_SIGNATURES[name]
            source = "curated"
        if signature is None and is_function:
            derived = _usage_signature(name, census)
            if derived is not None:
                params, codomain = derived
                signature = f"({', '.join(params)}) -> {codomain}"
                source = "usage"
        if signature is None:
            signature = "(any+) -> any" if is_function else "any"
            source = "fallback"

        rec = {
            "fungrimId": sd["id"] if sd else None,
            "description": sd["description"] if sd else None,
            "arity": _arity_field(arities),
            "signature": signature,
            "signatureSource": source,
            "signatureInferred": source != "fallback",
            "domainTable": domain_table,
            "wikidata": None,
        }
        extra = [fn for fn in fungrim_names if fn != name]
        if extra:
            rec = {"fungrimNames": extra, **rec}
        declarations[name] = rec

    # CE-known heads used by the corpus: audit section
    existing = {}
    for name in sorted(names & ce_known):
        rec = {}
        if name in reverse:
            rec["fungrimNames"] = sorted(reverse[name])
        if name in ("Erf", "Erfc"):
            rec["note"] = ("CE numeric kernel is ~1e-7 accurate "
                           "(SPIKE-DECISIONS.md #15); tolerance >= 1e-6 "
                           "for numeric validation")
        existing[name] = rec

    doc = {
        "generator": GENERATOR,
        "declarations": declarations,
        "existing": existing,
    }
    return doc, uncovered


def write(doc, outdir):
    path = os.path.join(outdir, "declarations.json")
    with open(path, "w", newline="\n") as f:
        json.dump(doc, f, indent=1, ensure_ascii=True)
        f.write("\n")


def summarize(doc):
    decls = doc["declarations"]
    by_source = {}
    for rec in decls.values():
        by_source[rec["signatureSource"]] = \
            by_source.get(rec["signatureSource"], 0) + 1
    return {
        "shellCount": len(decls),
        "existingCount": len(doc["existing"]),
        "signatureSources": dict(sorted(by_source.items())),
        "withDomainTable": sum(1 for r in decls.values()
                               if r["domainTable"]),
    }
